# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
#   pull_request:
#     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x' 
      - run: npm install
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@master
        with: # Set the secret as an input
          args: deploy --only hosting
        env: # Or as an environment variable
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
