# This is a basic workflow to help you get started with Actions

name: Build and Deploy 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    name: Build and Deploy
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install dependencies 
        run: npm install
      - name: Firebase Trigger
        uses: w9jds/firebase-trigger@master
        with:
          args: deploy
        env: 
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
